# Generated by Django 4.0.2 on 2022-02-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_submission_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='note',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
