# Generated by Django 4.0.3 on 2022-03-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_remove_submission_note_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(1, 'Multi Options'), (2, 'Text Input')], default=1),
        ),
    ]
