# Generated by Django 4.0.3 on 2022-03-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='note',
            field=models.TextField(blank=True, default=None,null=True),
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
